### ISSUE TITLE
Fail to schedule an email ??

### ISSUE THREAD

**Issue by cryoguy** [bandresen/mu4e-send-delay#13]
I have 3 accounts, 2 gmails and one exchange server. I can not seem to make mu4e-send-delay work and this is what I am getting.

If I try to schedule an email from exchange account, I got following message.
Saving file /.../mail/Drafts/cur/1489718313.3ed505347ccd2a4a.sagittarius:2,DS...
Wrote /.../mail/Drafts/cur/1489718313.3ed505347ccd2a4a.sagittarius:2,DS
[mu4e] Saved (5 lines)
mu4e-send-delay: (error [mu4e] unsupported type for ("/Exchange/Sent"))
[mu4e] Mail scheduled for sending at: mu4e-send-delay: (error [mu4e] unsupported type for ("/Exchange/Sent"))
If I try to schedule from Gmail account, I got this:
Saving file /.../mail/Drafts/cur/1489718675.87ee579c4f98342c.sagittarius:2,DS...
Wrote /.../mail/Drafts/cur/1489718675.87ee579c4f98342c.sagittarius:2,DS
[mu4e] Saved (5 lines)
mu4e-send-delay: (error [mu4e] Cannot set folder mu4e-sent-folder, account for MSG nil not detected)
[mu4e] Mail scheduled for sending at: mu4e-send-delay: (error [mu4e] Cannot set folder mu4e-sent-folder, account for MSG nil not detected)

**Comment by bennyandresen** [comment]
At this point I don't know what would be causing this, as it's occuring inside mu4e-send-delay-schedule-this-mail

What happens if you invoke M-x mu4e-send-delay-send-and-exit with C-u?
If that doesn't work the regular mu4e mail sending setup needs to be fixed first.

If this isn't it and it's a problem with mu4e-send-delay: =M-x toggle-debug-on-error RET=, run it again and provide the backtrace.

**Comment by cryoguy** [comment]
if I invoke M-x mu4e-send-delay-send-and-exit with C-u, I got following with debug mode on.  update: mu4e did send out the email.

Debugger entered--Lisp error: (error "Error 11: mu_store_get_msg: xapian error 'Document 75581 not found'")
  signal(error ("Error 11: mu_store_get_msg: xapian error 'Document 75581 not found'"))
  error("Error %d: %s" 11 "mu_store_get_msg: xapian error 'Document 75581 not found'")
  mu4e-error-handler(11 "mu_store_get_msg: xapian error 'Document 75581 not found'")
  mu4e~proc-filter(#<process *mu4e-proc*> "\37651\377(:error 11 :message \"mu_store_get_msg: xapian error 'Document 75581 not found'\")\n")

I think the problem is related to mu4e-multi since I got this when I schedule an email. I do not know how to resolve this though.
Error running timer ‘mu4e-send-delay-send-queue’: (error #("[mu4e] Cannot set folder mu4e-drafts-folder, account for MSG nil not detected" 1 5 (face mu4e-title-face)))

**Comment by bennyandresen** [comment]
mu4e-send-delay only supports the native way of handling multiple accounts which is mu4e-context.

These messages above are not generated by mu4e-send-delay. It looks like an issue with the general mu4e setup.

Also please keep in mind that adding the documented timer before things are working properly will mean you have to clear the timer (restart emacs) or your current Emacs session will continue to error.

**Comment by cryoguy** [comment]
OK,I see.  I am using mu4e-multi. Any future plan to update the package? 

Also do you mean that scheduling timer is only good for current session? say I schedule an email for 2 hours, and if I restart the emacs for whatever reason, the schedule will reset for another 2 hours?

**Comment by bennyandresen** [comment]
as mu4e-multi hasn't been updated since 2014 I don't have any plans to update it for that purpose.

To your scheduling question: No. I was just saying if mu4e-send-delay isn't working properly as in your case then the timer that is created will be messing up your current session, because it will be checking in the background all the time for jobs to process.

Upon scheduling the absolute time is written in the mail (instead of 2 hour relative) so even if you've restarted Emacs in between. As long as the code for the mu4e-send-delay-timer is evaluated it should run it.
